-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bookdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bookdb` ;

-- -----------------------------------------------------
-- Schema bookdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookdb` DEFAULT CHARACTER SET utf8 ;
USE `bookdb` ;

-- -----------------------------------------------------
-- Table `book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `book` ;

CREATE TABLE IF NOT EXISTS `book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  `series` TINYINT NOT NULL,
  `number` INT NULL,
  `genre` VARCHAR(45) NOT NULL,
  `page_count` INT NULL,
  `description` VARCHAR(15000) NOT NULL,
  `date_created` DATETIME NOT NULL,
  `date_updated` DATETIME NULL,
  `series_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS bookuser@localhost;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'bookuser'@'localhost' IDENTIFIED BY 'bookuser';

GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE * TO 'bookuser'@'localhost';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `book`
-- -----------------------------------------------------
START TRANSACTION;
USE `bookdb`;
INSERT INTO `book` (`id`, `title`, `author`, `series`, `number`, `genre`, `page_count`, `description`, `date_created`, `date_updated`, `series_name`) VALUES (1, 'Test', 'Test', 0, NULL, 'Test', null, 'Test', '2022-08-12', NULL, 'Test');
INSERT INTO `book` (`id`, `title`, `author`, `series`, `number`, `genre`, `page_count`, `description`, `date_created`, `date_updated`, `series_name`) VALUES (2, 'Upended Life', 'Eryn R Flynn', 1, 1, 'Paranormal Romance', 261, 'My name is Tamsin Vale and my life is about to get real… Really complicated and ridiculously dangerous. Which is almost funny given at nineteen I already know too much of the darkness of the world and people, the secrets they keep.\n\nOr so I thought.\n\nTurns out those quirky abilities I’ve been keeping secret expose me to a world I didn’t know existed. Sure, I knew I wasn’t human—but how exactly do I find out more without ending up in the wrong hands?\n\nAnd I’m not so sure I’m in the right hands now given some of the reactions to finding me. They say I’m the last fairy. I’m not sure I should trust them when their thoughts are mostly of power and how to use me.\n\nBut I’m also not sure I have much of a choice. My powers are dangerous and I don’t know how to use them. They promise to teach me what I need to know and give me a chance at something I’ve never had before.\n\nA normal life. I don’t think anything about Artemis University and those who attend is normal, but it’s still better than the life I’ve been living if they keep half their promises.\n\nI think hoping they’ll keep half is generous.\n\nArtemis University is a hot burning reverse harem, university-age paranormal academy series with darker elements, strong language, violence, and a heroine who follows her own moral compass of what is right… And who she ends up giving her heart to.', '2022-08-13', NULL, 'Artemis University');
INSERT INTO `book` (`id`, `title`, `author`, `series`, `number`, `genre`, `page_count`, `description`, `date_created`, `date_updated`, `series_name`) VALUES (3, 'Dune', 'Frank Herbert', 1, 1, 'Science Fiction', 704, 'Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the “spice” melange, a drug capable of extending life and enhancing consciousness. Coveted across the known universe, melange is a prize worth killing for....\n\nWhen House Atreides is betrayed, the destruction of Paul’s family will set the boy on a journey toward a destiny greater than he could ever have imagined. And as he evolves into the mysterious man known as Muad’Dib, he will bring to fruition humankind’s most ancient and unattainable dream. \n\nA stunning blend of adventure and mysticism, environmentalism and politics, Dune won the first Nebula Award, shared the Hugo Award, and formed the basis of what is undoubtedly the grandest epic in science fiction.', '2022-08-13', NULL, 'Dune Chronicles');
INSERT INTO `book` (`id`, `title`, `author`, `series`, `number`, `genre`, `page_count`, `description`, `date_created`, `date_updated`, `series_name`) VALUES (4, 'On This Day in History Sh!t Went Down', 'James Fell', 1, 1, 'History', 393, 'Sh!t happens. Every day.Mae West was sent to jail for “corrupting the morals of youth” with her first Broadway play. When participation in the Hitler Youth became mandatory in Germany, groups of teen “pirates” rebelled. Muhammad Ali refused to “drop bombs and bullets on brown people” in Vietnam. A dog sled relay carried life-saving medicine 674 miles through –50 temperatures to rescue children dying from diphtheria. The Dionne Quintuplets were stolen by the Canadian government and displayed like zoo animals for profit. Indian princess Noor Inayat Khan was one of the most successful spies against the Nazis in World War II. A children’s television show called Caillou tortured parents for more than a decade . . .Sh!t goes down every single day of the year, year after year. Sometimes it’s a battle that changes the course of history, other times it’s a life-saving medical advancement. Bravery is counter-balanced with cowardice. There is slavery and there is self-sacrifice. History is replete with deeds both noble and despicable. Some were motivated by greed, others generosity. Many dedicated themselves to the art of killing, while others focused their efforts on curing. There have been grave mistakes and moments of greatness. Confrontation and cooperation.Early in the twentieth century Spanish philosopher George Santayana wrote, “Those who cannot remember the past are condemned to repeat it.” But history serves not just as a warning; it also offers encouragement. Humanity is not endless suck. There is inspiration to be found amidst the atrocities.On This Day in History Sh!t Went Down will significantly expand your knowledge of world history in the most hilarious and profane way possible.', '2022-08-14', NULL, 'History Sh!t');
INSERT INTO `book` (`id`, `title`, `author`, `series`, `number`, `genre`, `page_count`, `description`, `date_created`, `date_updated`, `series_name`) VALUES (5, 'Throne of Glass', 'Sarah J. Mass', 1, 1, 'Fantasy', 416, 'After serving out a year of hard labor in the salt mines of Endovier for her crimes, 18-year-old assassin Celaena Sardothien is dragged before the Crown Prince. Prince Dorian offers her her freedom on one condition: she must act as his champion in a competition to find a new royal assassin.\n\nHer opponents are men-thieves and assassins and warriors from across the empire, each sponsored by a member of the king\'s council. If she beats her opponents in a series of eliminations, she\'ll serve the kingdom for three years and then be granted her freedom.\n\nCelaena finds her training sessions with the captain of the guard, Westfall, challenging and exhilirating. But she\'s bored stiff by court life. Things get a little more interesting when the prince starts to show interest in her... but it\'s the gruff Captain Westfall who seems to understand her best.\n\nThen one of the other contestants turns up dead... quickly followed by another. Can Celaena figure out who the killer is before she becomes a victim? As the young assassin investigates, her search leads her to discover a greater destiny than she could possibly have imagined.', '2022-08-14', NULL, NULL);
INSERT INTO `book` (`id`, `title`, `author`, `series`, `number`, `genre`, `page_count`, `description`, `date_created`, `date_updated`, `series_name`) VALUES (6, 'The Oddysey', 'Homer', 0, NULL, 'Mythology', 541, 'If the Iliad is the world\'s greatest war epic, the Odyssey is literature\'s grandest evocation of an everyman\'s journey through life. Odysseus\' reliance on his wit and wiliness for survival in his encounters with divine and natural forces during his ten-year voyage home to Ithaca after the Trojan War is at once a timeless human story and an individual test of moral endurance.', '2022-08-14', NULL, NULL);
INSERT INTO `book` (`id`, `title`, `author`, `series`, `number`, `genre`, `page_count`, `description`, `date_created`, `date_updated`, `series_name`) VALUES (7, 'Interview with the Vampire', 'Anne Rice', 1, 1, 'Paranormal', 352, 'The time is now.\n\nWe are in a small room with the vampire, face-to-face, as he speaks - as he pours out the hypnotic, shocking, moving, and erotically charged confessions of his first 200 years as one of the living dead...\n\nHe speaks quietly, plainly, even gently...carrying us back to the night when he departed human existence as heir - young, romantic, cultivated - to a great Louisiana plantation, and was inducted by the radiant and sinister Lestat into the other, the \"endless\", life...learning first to sustain himself on the blood of cocks and rats caught in the raffish streets of New Orleans, then on the blood of human beings...to the years when, moving away from his final human ties under the tutelage of the hated yet necessary Lestat, he gradually embraces the habits, hungers, feelings of vampirism: The detachment, the hardened will, the \"superior\" sensual pleasures.\n\nHe carries us back to the crucial moment in a dark New Orleans street when he finds the exquisite lost young child Claudia, wanting not to hurt but to comfort her, struggling against the last residue of human feeling within him...\n\nWe see how Claudia in turn is made a vampire - all her passion and intelligence trapped forever in the body of a small child - and how they arrive at their passionate and dangerous alliance, their French Quarter life of opulence: Delicate Grecian statues, Chinese vases, crystal chandeliers, a butler, a maid, a stone nymph in the hidden garden court...night curving into night with their vampire senses heightened to the beauty of the world, thirsting for the beauty of death - a constant stream of vulnerable strangers awaiting them below...\n\nWe see them joined against the envious, dangerous Lestat, embarking on a perilous search across Europe for others like themselves, desperate to discover the world they belong to, the ways of survival, to know what they are and why, where they came from, what their future can be...\n\nWe follow them across Austria and Transylvania, encountering their kind in forms beyond their wildest imagining...to Paris, where footsteps behind them, in exact rhythm with their own, steer them to the doors of the Théâtre des Vampires - the beautiful, lewd, and febrile mime theatre whose posters of penny-dreadful vampires at once mask and reveal the horror within...to their meeting with the eerily magnetic Armand, who brings them, at last, into intimacy with a whole brilliant and decadent society of vampires, an intimacy that becomes sudden terror when they are compelled to confront what they have feared and fled...', '2022-08-14', NULL, 'The Vampire Chronicles');
INSERT INTO `book` (`id`, `title`, `author`, `series`, `number`, `genre`, `page_count`, `description`, `date_created`, `date_updated`, `series_name`) VALUES (8, 'Two Years Eight Months and Twenty-Eight Nights', 'Salman Rushdie', 0, NULL, 'Folklore', 304, 'In the near future, after a storm strikes New York City, the strangenesses begin. A down-to-earth gardener finds that his feet no longer touch the ground. A graphic novelist awakens in his bedroom to a mysterious entity that resembles his own sub–Stan Lee creation. Abandoned at the mayor’s office, a baby identifies corruption with her mere presence, marking the guilty with blemishes and boils. A seductive gold digger is soon tapped to combat forces beyond imagining.\n\nUnbeknownst to them, they are all descended from the whimsical, capricious, wanton creatures known as the jinn, who live in a world separated from ours by a veil. Centuries ago, Dunia, a princess of the jinn, fell in love with a mortal man of reason. Together they produced an astonishing number of children, unaware of their fantastical powers, who spread across generations in the human world.\n\nOnce the line between worlds is breached on a grand scale, Dunia’s children and others will play a role in an epic war between light and dark spanning a thousand and one nights—or two years, eight months, and twenty-eight nights. It is a time of enormous upheaval, in which beliefs are challenged, words act like poison, silence is a disease, and a noise may contain a hidden curse.\n\nInspired by the traditional “wonder tales” of the East, Salman Rushdie’s novel is a masterpiece about the age-old conflicts that remain in today’s world. Two Years Eight Months and Twenty-Eight Nights is satirical and bawdy, full of cunning and folly, rivalries and betrayals, kismet and karma, rapture and redemption.', '2022-08-14', NULL, NULL);
INSERT INTO `book` (`id`, `title`, `author`, `series`, `number`, `genre`, `page_count`, `description`, `date_created`, `date_updated`, `series_name`) VALUES (9, 'The Time of Tears', 'Jonathan Dominguez', 1, 1, 'Urban Fantasy', 322, 'Carnegie Sanders is a typical 19-year-old. He goes to college, he lives at home and in a dorm, has a crush on a girl he went to high school with, and has no idea what to do with his life. Life is normal. Then hydrogen bombs decimate the globe, and robed beings start wiping out everyone else lucky enough to live in rural America. In his small town in southern Arizona, Carnegie realizes survival is more than chance. Running on instinct, Erin, Santana, and Carnegie find the decimation of their people to be the beginning of change and tragedy never witnessed in history. As the world resets, Carnegie, Erin, and Santana face odds that would consume them, if not for new relationships forged. Creatures from fantastic stories lost in time and translation seek to keep humanity in check as Carnegie seeks a place to call home, a place to be safe. No one is safe as sinister forces work behind the veil of secrecy, and everyone in Carnegie’s new circle will experience turmoil. Lost in the new races of lore calling themselves the Nine, Carnegie is thrust into becoming someone he isn’t ready to be for those who rely on him. Set in the dynamic landscape of the American Southwest, and from deserts to mountains and even under the earth itself, no where is safe. Fighting for survival is just the beginning. Nothing has prepared them for this time.A time of confusion.A time of loss.And a time of tears.', '2022-08-14', NULL, 'The Time of Tears');
INSERT INTO `book` (`id`, `title`, `author`, `series`, `number`, `genre`, `page_count`, `description`, `date_created`, `date_updated`, `series_name`) VALUES (10, 'The Looking Glass Wars', 'Frank Beddor', 1, 1, 'YA Epic Fantasy', 330, 'The Myth: Alice was an ordinary girl who stepped through the looking glass and entered a fairy-tale world invented by Lewis Carroll in his famous storybook. The Truth: Wonderland is real. Alyss Heart is the heir to the throne, until her murderous aunt Redd steals the crown and kills Alyss? parents. To escape Redd, Alyss and her bodyguard, Hatter Madigan, must flee to our world through the Pool of Tears. But in the pool Alyss and Hatter are separated. Lost and alone in Victorian London, Alyss is befriended by an aspiring author to whom she tells the violent, heartbreaking story of her young life. Yet he gets the story all wrong. Hatter Madigan knows the truth only too well, and he is searching every corner of our world to find the lost princess and return her to Wonderland so she may battle Redd for her rightful place as the Queen of Hearts.', '2022-08-14', NULL, 'The Looking Glass Wars');

COMMIT;

